### ISSUE TITLE
Human Evaluation Data

### ISSUE THREAD

**Issue by jvamvas** [facebookresearch/m-amr2text#1]
Thank you for sharing so many resources from your paper.
In addition to the data already provided, I believe that the **data from the human evaluation (Table 3)** could be of enormous value to the community.

In recent years it has become common to compare similarity metrics, such as BLEU or BERTScore, regarding their correlation to human judgements. However, such comparisons are usually done in English only. The data from Table 3 would allow to extend this type of research to 17 more languages!

Please let me know whether the data could be made available. I am sure many research projects could greatly benefit from the human ratings you have collected.

**Comment by huihuifan** [comment]
[human_eval_amr_results.zip](https://github.com/facebookresearch/m-amr2text/files/7982658/human_eval_amr_results.zip)

**Comment by jvamvas** [comment]
Hi @huihuifan, thank you so much for your quick response!
The following data are currently missing:

- References and hypotheses for English, German and French
- Annotations for English

If it's not too much trouble, could you please also upload these data?
